# -*- coding: utf-8 -*-
"""Lab04_21201359.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13tnv2MybDd_r6HrQ9H8JXlrLTOTF4xWg
"""

class Patient:
  def __init__(self,id,name,age,blood_group):
    self.id = id
    self.name = name
    self.age = age
    self.b_g = blood_group

class WRM:
  def __init__(self):
    self.dummy_head = Patient(None,None,None,None)
    self.dummy_head.next = self.dummy_head
    self.dummy_head.prev = self.dummy_head
    self.tail = self.dummy_head

  def RegisterPatient(self,id,name,age,blood_group):
    new_patient = Patient(id,name,age,blood_group)
    new_patient.next = self.dummy_head
    new_patient.prev = self.tail
    self.tail.next = new_patient
    self.tail = new_patient
    temp =self.tail
    print("A patient has been successfully registered.")
    print(f"ID: {temp.id}\nName: {temp.name}\nAge: {temp.age}\nBlood Group: {temp.b_g}")

  def ServePatient(self):
    if self.dummy_head.next == None:
      return
    else:
      print(self.dummy_head.next.name,"has been served.")
      self.dummy_head.next=self.dummy_head.next.next

  def CancelAll(self):
    self.dummy_head.next = None
    self.dummy_head.prev = None
    print("Success")

  def CanDoctorGoHome(self):
    if self.dummy_head == self.dummy_head.next or self.dummy_head.next == None:
      print("Yes")
    elif self.dummy_head != self.dummy_head.next and self.dummy_head != None:
      print("No")

  def ShowAllPatient(self):
    print("List of all registered patients:")
    if self.dummy_head != None:
      temp = self.dummy_head.next
      if self.dummy_head.next != None:
        while temp != self.dummy_head:
          print(f"ID: {temp.id}\nName: {temp.name}\nAge: {temp.age}\nBlood Group: {temp.b_g}")
          temp = temp.next
      else:
        return
    else:
      print("All patients has been cancelled.")

  def ReverseTheLine(self):
    if self.dummy_head.next == self.dummy_head:
      return
    first = self.dummy_head.next
    last = self.tail

    while first != last and first.prev != last:
      first.id, last.id = last.id, first.id
      first.name, last.name = last.name, first.name
      first.b_g, last.b_g = last.b_g, first.b_g
      first = first.next
      last = last.prev
    print("The line has been reversed successfully.")

#Driver Code
print("==============================================")
patient_1 = WRM()
patient_1.RegisterPatient(78620, "Tuba", 21, "A-")
patient_1.RegisterPatient(15903, "Kabir", 24, "B+")
patient_1.RegisterPatient(25791, "Ruban", 10, "O+")
patient_1.RegisterPatient(54336, "Ali", 36, "B+")
print("==============================================")
patient_1.ServePatient()
print("==============================================")
patient_1.ShowAllPatient()
print("==============================================")
patient_1.ServePatient()
patient_1.ServePatient()
print("==============================================")
patient_1.CanDoctorGoHome()
print("==============================================")
patient_1.RegisterPatient(76221, "Ruhana", 39, "A+")
patient_1.RegisterPatient(65321, "Mahira", 25, "B-")
patient_1.RegisterPatient(21168, "Muntasir", 22, "O-")
print("==============================================")
patient_1.ReverseTheLine()
print("==============================================")
patient_1.CancelAll()
print("==============================================")
patient_1.ShowAllPatient()
patient_1.ServePatient()
patient_1.ServePatient()
# patient_1.ServePatient()
# patient_1.ServePatient()
print("==============================================")
patient_1.CanDoctorGoHome()